source ENV['GEM_SOURCE'] || "https://rubygems.org"

group :test do
  gem "rake"
  gem "puppet", '>= 5.5', '< 6.0'
  gem "rspec"
  gem "rspec-puppet"
  gem "rspec-puppet-facts"
  gem "rspec-puppet-utils"
  gem "rspec-puppet-augeas"
  gem "puppetlabs_spec_helper", '>= 1.2.0'
  gem "jimdo-rspec-puppet-helpers"
  gem "metadata-json-lint"
  gem 'simplecov', '>= 0.11.0', require: false, group: :test
  gem 'simplecov-console'
  gem 'codecov'
  gem 'semantic_puppet'
  gem 'facter', '>= 1.7.0'
  gem 'puppet-strings'
  gem 'nokogiri'

  gem 'puppet-lint', '>= 1.0.0'
  gem "puppet-lint-absolute_classname-check"
  gem "puppet-lint-leading_zero-check"
  gem "puppet-lint-trailing_comma-check"
  gem "puppet-lint-version_comparison-check"
  gem "puppet-lint-classes_and_types_beginning_with_digits-check"
  gem "puppet-lint-unquoted_string-check"
  gem 'puppet-lint-resource_reference_syntax'

  gem 'json_pure', '<= 2.0.1' if RUBY_VERSION < '2.0.0'

  gem 'rspec_junit_formatter'
  gem 'git'

  # rspec must be v2 for ruby 1.8.7
  if RUBY_VERSION >= '1.8.7' && RUBY_VERSION < '1.9'
    gem 'rspec', '~> 2.0'
    gem 'rake', '~> 10.0'
  elsif RUBY_VERSION < '2.2.0'
    gem "rubocop", "< 0.60.0"
  else
    # rubocop:disable Bundler/DuplicatedGem
    gem "rubocop-rails"
    # rubocop:enable Bundler/DuplicatedGem
  end
end

group :development do
  gem "better_errors"
  gem "binding_of_caller"
  gem "puppet-blacksmith"
  gem "guard-rake" if RUBY_VERSION >= '2.2.5' # per dependency https://rubygems.org/gems/ruby_dep
  gem "listen", "~> 3.0.0"
end

group :system_tests do
  if RUBY_VERSION < '2.2.0'
    gem "beaker", "< 3.0.0"
    gem "beaker-rspec", "< 6.0"
  else
    # rubocop:disable Bundler/DuplicatedGem
    gem "beaker"
    gem "beaker-rspec"
    # rubocop:enable Bundler/DuplicatedGem
  end
  gem "beaker-puppet_install_helper"
end
