name: Run pdk test unit

on:
  - push
  - pull_request

jobs:
  build:
    strategy:
      matrix:
        version: ["5.5.22", "6.28,0", "7.24.0"]
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2

    - name: Run unit tests
      uses: puppets-epic-show-theatre/action-pdk-test-unit@v1
      with:
        puppet-version: ${{ matrix.version }}
        # [optional]
        # A string indicating the Puppet version to validate against, such as "5.4.2" or "5.5".
        pe-version: ""
        # [optional]
        # A string indicating the PE version to validate against, such as "2017.3.5" or "2018.1".
